[theme]
primaryColor = "#F3B338"        # Amarelo ouro
backgroundColor = "#F5F5F5"     # Cinza claro
secondaryBackgroundColor = "#E0E0E0"  # Cinza m√©dio
textColor = "#506867"           # Cinza escuro para o texto
font = "sans serif"